name: "Image Update of an ECS Service"
description: "Updates an existing ECS Service with a new image"
inputs:
  image:
    required: true
  family:
    required: true
  cluster:
    required: true
  service:
    required: true
  version:
    required: false
  versionMsg:
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
