name: "Upload Web App To S3 + CloudFront"
description: "Upload Site to S3 + CloudFront (optional)"
inputs:
  stage:
    description: The semantical AWS Deployment stage, e.g. prod, beta, test
    required: true
  removeBucketFiles:
    description: "Should the existing bucket be emptied before updating?"
    default: "false"
  app:
    description: "The SPA app name to be deployed"
    required: true
  project:
    description: "The context of your app, which acts as a prefix for the AWS resources, e.g. project name"
    required: true
  apexDomain:
    description: "The naked/root domain with ending, where the app should be deployed at. Example: domain.com"
    required: true
  appSubDomain:
    description: "The subdomain part, where the app should be deployed at WITHOUT the root domain. Example: vehicles"
    default: ""
  buildPath:
    description: "The local path to the build/dist folder of your app. This folder will be copied to S3."
    required: true
  tagsFileLocation:
    description: "The location of the tags, which should be updated or set"

runs:
  using: "node20"
  main: "dist/index.js"
